openapi: 3.0.1
info:
  title: SAMPRO API
  description: API para generación de parleys, clasificación por nivel y evaluación predictiva.
  version: "1.0.0"
servers:
  - url: https://gpt-sampro-clean.onrender.com
paths:
  /parleys_por_nivel:
    get:
      summary: Obtener parleys clasificados por nivel
      responses:
        '200':
          description: Lista de parleys
  /evaluacion:
    get:
      summary: Obtener evaluación predictiva diaria
      responses:
        '200':
          description: Resumen con ROI, aciertos, etc.
  /predict:
    post:
      summary: Predecir ganador basado en métricas sabermétricas
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                obp_diff:
                  type: number
                slg_diff:
                  type: number
                era_diff:
                  type: number
                fip_diff:
                  type: number
                equipo_local:
                  type: string
      responses:
        '200':
          description: Resultado de predicción
