openapi: 3.0.0
info:
  title: GPT-SANPRO
  version: "1.0"
  description: API de apuestas deportivas inteligentes
servers:
  - url: https://gpt-sanpro-clean.onrender.com

paths:
  /parley_seguro_vida_json:
    get:
      summary: Devuelve json con el parley seguro
      responses:
        '200':
          description: Lista de parlays

  /prediccion:
    get:
      summary: Predicción con goles simulados
      parameters:
        - name: goles_local
          in: query
          schema:
            type: number
        - name: goles_visita
          in: query
          schema:
            type: number
      responses:
        '200':
          description: Probabilidades calculadas
