openapi: 3.0.1
info:
  title: SAMPRO API
  description: API para generaci칩n de parleys y an치lisis predictivo.
  version: "1.0.0"
servers:
  - url: https://gpt-sampro-clean.onrender.com
paths:
  /parleys_por_nivel:
    get:
      summary: Obtener parleys por nivel
      responses:
        '200':
          description: OK
  /evaluacion:
    get:
      summary: Evaluaci칩n predictiva
      responses:
        '200':
          description: OK
  /predict:
    post:
      summary: Predicci칩n personalizada
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                obp_diff: { type: number }
                slg_diff: { type: number }
                era_diff: { type: number }
                fip_diff: { type: number }
                equipo_local: { type: string }
      responses:
        '200':
          description: Resultado
